#!/usr/bin/env node
const path = require("path");
const { Store } = require("./src/store.js");
const { parseArgs, run } = require("./src/cli.js");

const STORE_CONFIG = {
	cacheDir: path.join(__dirname, ".cache")
};

run(new Store(STORE_CONFIG), parseArgs(process.argv));
